# -*- mode: ruby -*-
# vi: set ft=ruby :
#
SUBNET="10.0.10"
#
vmcount=1

Vagrant.configure(2) do |config|
  foremanIP = "#{SUBNET}.100"
$foremanInstall= <<SCRIPT
sudo apt-get -y install ca-certificates
sudo wget https://apt.puppetlabs.com/puppetlabs-release-jessie.deb
sudo dpkg -i puppetlabs-release-jessie.deb
sudo echo "deb http://deb.theforeman.org/ jessie 1.8" > /etc/apt/sources.list.d/foreman.list
sudo echo "deb http://deb.theforeman.org/ plugins 1.8" >> /etc/apt/sources.list.d/foreman.list
sudo wget -q http://deb.theforeman.org/pubkey.gpg -O- | apt-key add -
sudo apt-get update && apt-get -y install foreman-installer
sudo foreman-installer --foreman-admin-password=bogroll
sudo puppet agent --test
sudo echo "#{SUBNET}.101 client.myhouse.local client" |sudo tee -a /etc/hosts
sudo systemctl stop ntp
SCRIPT
$clienthelper= <<SCRIPT
sudo echo "#{foremanIP} foreman.myhouse.local foreman" |sudo tee -a /etc/hosts
sudo yum install -y puppet
sudo sed -i 's/PUPPET_SERVER.*/PUPPET_SERVER=foreman.myhouse.local/g'
sudo chkconfig puppet on
sudo service puppet start
sudo puppet agent --test
SCRIPT
	config.vm.define "foreman_server" do |f|
		f.vm.provider "virtualbox" do |v|
			v.name = "Foreman Server"
		end
		f.vm.box = "mokote/debian-8"
		f.vm.hostname = "foreman.myhouse.local"
		f.vm.network "private_network", ip: "#{foremanIP}"
		f.vm.network :forwarded_port, guest: 80, host: 8082
		f.vm.network :forwarded_port, guest: 443, host: 8083
		f.vm.network :forwarded_port, guest: 8443, host: 8443
		f.vm.provision "shell", inline: $foremanInstall
	end
	config.vm.define "client" do |c|
		c.vm.provider "virtualbox" do |v|
			v.name = "puppet client"
		end
		c.vm.box = "chef/centos-6.5"
		c.vm.hostname = "client.myhouse.local"
		c.vm.network "private_network", ip: "#{SUBNET}.101"
		c.vm.provision "shell", inline: $clienthelper
	end
end