# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# By kb21 . Rough instructions:
# 1  install vagrant
# 2  install virtualbox.
# 3  make a folder, copy this file into it.
# 4  at a command prompt type "vagrant up"
# 5  watch it build
#
# If you want to shut the farm down use "vagrant halt"
# To nuke it all from orbit use "vagrant destroy", you can rebuild it with "vagrant up" again

# Once it's up you can ssh to the server on 127.0.0.1:2222, clients start at port 2200
# user: vagrant pass: vagrant
# also all machines share a /vagrant directory. This is the dir on your local machine where you put the Vagrantfile


# change vmcount to increase number of clients
# subnet can be changed if it conflicts with your home one. PLEASE (for the moment) keep it in 10.0.x.x
vmcount=2
SUBNET="10.0.10"
#

Vagrant.configure(2) do |config|
  cfEngineMaster = "#{SUBNET}.100"
  config.vm.define "cfserv" do |cfserv|
    cfserv.vm.provider "virtualbox" do |v|
        v.name = "CFEngine Server"
    end
    cfserv.vm.box = "chef/centos-6.5"
    cfserv.vm.network "private_network", ip: "#{cfEngineMaster}"
    cfserv.vm.network :forwarded_port, guest: 80, host: 8082
    cfserv.vm.hostname = "cfserv"
    cfserv.vm.provision "cfengine" do |cf|
      cf.am_policy_hub = true
      end
  end
(1..vmcount.to_i).each do |host|
  hosts = "client#{host}"
  config.vm.define hosts do |cfcl1|
    cfcl1.vm.provider "virtualbox" do |v|
        v.name = "CFEngine client#{host}"
    end
    cfcl1.vm.box = "chef/centos-7.0"
    cfcl1.vm.hostname = hosts
    cfcl1.vm.network "private_network", ip: "#{SUBNET}.#{host + 10}"
    cfcl1.vm.provision "cfengine" do |cf|
      cf.policy_server_address = "#{cfEngineMaster}"
    end
  
  end
 end
end
