# -*- mode: ruby -*-
# vi: set ft=ruby :

# change vmcount to increase number of clients
# subnet can be changed if it conflicts with your home one. PLEASE (for the moment) keep it in 10.0.x.x
vmcount=2
SUBNET="10.0.10"
#
$masterFiles= <<SCRIPT
sudo cp -rf /vagrant/cf/* /var/cfengine/masterfiles
sudo cp -rf /var/cfengine/masterfiles/* /var/cfengine/inputs/
SCRIPT
Vagrant.configure(2) do |config|
  cfEngineMaster = "#{SUBNET}.100"
  config.vm.define "cfserv" do |cfserv|
    cfserv.vm.provider "virtualbox" do |v|
        v.name = "CFEngine Server"
    end
    cfserv.vm.box = "chef/centos-6.5"
    cfserv.vm.network "private_network", ip: "#{cfEngineMaster}"
    cfserv.vm.network :forwarded_port, guest: 80, host: 8082
    cfserv.vm.hostname = "cfserv"
    cfserv.vm.provision "cfengine" do |cf|
      cf.am_policy_hub = true
      end
    cfserv.vm.provision "shell", inline: $masterFiles
  end
(1..vmcount.to_i).each do |host|
  hosts = "client#{host}"
  config.vm.define hosts do |cfcl1|
    cfcl1.vm.provider "virtualbox" do |v|
        v.name = "CFEngine client#{host}"
    end
    cfcl1.vm.box = "chef/centos-7.0"
    cfcl1.vm.hostname = hosts
    cfcl1.vm.network "private_network", ip: "#{SUBNET}.#{host + 10}"
    cfcl1.vm.provision "cfengine" do |cf|
      cf.policy_server_address = "#{cfEngineMaster}"
    end
  
  end
 end
end
